### ISSUE TITLE
Dupe bug with fancy workbench GUI.

### ISSUE THREAD

**Issue by Freelanci** [Nuchaz/BiblioCraft#347]
I am currently running the Revolution 2 modpack (MC version 1.7.10), and am an admin for a server network, I was told to look into a very easy dupe glitch involving the fancy workbench. The version of Bibliocraft this was tested on is 1.11.4.

As for the details of how the duplication glitch is pulled off, it's as simple as right-clicking the fancy workbench to open it's GUI, put any stackable item in the first slot of the player's hotbar, and shift left-click said item. Providing the item is stackable, it is moved to another spot in the player's inventory, typically the second slot of the hotbar, and will have doubled in stack size (up to 64).

Here's some simple screenshots for the dupe in action:
http://puu.sh/nydUN/856f59a4f7.png
http://puu.sh/nydWZ/f88f50458e.png

**Comment by KaneHart** [comment]
Issue not fixed 28 days later. Massive issue.

**Comment by Nuchaz** [comment]
I'll look into this. Definitely not good. I've been meaning to read over the issues here on the github, but didn't have time during the school semester and I have been busy on the 1.8.x update since that ended. I'll think about doing another update for Minecraft 1.7.10 to address this if I can.

**Comment by mcdodge34** [comment]
Yup, needs to check it out a video is going to be viral soon there, it shows how to abuse the system really quickly, just tested it on my server and it works, I'll have to figure out how to disable the crafting of this fancy workbench for now.

https://www.youtube.com/watch?v=tRmLGYiEJwM

**Comment by Nuchaz** [comment]
Fixed in BiblioCraft v1.11.5

**Comment by Natesky9** [comment]
Unfortunately, dupe bug still exists with v1.11.5.
Bibliocraft Fancy Workbench consumes any identical item to stack item on grid, duplicating the stored recipe, creating copies of the original, *regardless* of nbt data or maximum stack size
