### ISSUE TITLE
Framed Fancy Sign crashes on opening GUI

### ISSUE THREAD

**Issue by Partonetrain** [Nuchaz/BiblioCraft#579]
Doesn't crash with unframed (like, default texutre) Framed Fancy Signs.

`--- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
  GottaGoFastLoader (gottagofast-1.1.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 6/9/18 2:42 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at jds.bibliocraft.gui.GuiFancySign.saveTextLines(GuiFancySign.java:469)
	at jds.bibliocraft.gui.GuiFancySign.func_146281_b(GuiFancySign.java:219)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:987)
	at net.minecraft.client.entity.EntityPlayerSP.func_175159_q(EntityPlayerSP.java:335)
	at net.minecraft.client.entity.EntityPlayerSP.func_71053_j(EntityPlayerSP.java:328)
	at jds.bibliocraft.gui.GuiFancySign.func_73869_a(GuiFancySign.java:532)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at jds.bibliocraft.gui.GuiFancySign.saveTextLines(GuiFancySign.java:469)
	at jds.bibliocraft.gui.GuiFancySign.func_146281_b(GuiFancySign.java:219)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:987)
	at net.minecraft.client.entity.EntityPlayerSP.func_175159_q(EntityPlayerSP.java:335)
	at net.minecraft.client.entity.EntityPlayerSP.func_71053_j(EntityPlayerSP.java:328)
	at jds.bibliocraft.gui.GuiFancySign.func_73869_a(GuiFancySign.java:532)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)

-- Affected screen --
Details:
	Screen name: jds.bibliocraft.gui.GuiFancySign

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Partonetrain'/305364, l='MpServer', x=5252.64, y=54.00, z=1878.88]]
	Chunk stats: MultiplayerChunkCache: 439, 439
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (42,64,222), Chunk: (at 10,4,14 in 2,13; contains blocks 32,0,208 to 47,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4718439 game time, 5409328 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 130 total; [EntityBat['Bat'/305668, l='MpServer', x=5322.55, y=25.10, z=1819.46], EntityFishCod['Cod'/305412, l='MpServer', x=5174.51, y=54.77, z=1881.61], EntityPlayerSP['Partonetrain'/305364, l='MpServer', x=5252.64, y=54.00, z=1878.88], EntityMooshroom['Mooshroom'/305670, l='MpServer', x=5304.55, y=63.00, z=1886.36], EntityLatchedRenderer['unknown'/3, l='MpServer', x=5252.64, y=54.00, z=1878.88], EntityFishCod['Cod'/305415, l='MpServer', x=5279.50, y=43.00, z=1937.50], EntityMinecartChest['Minecart with Chest'/305671, l='MpServer', x=5313.50, y=24.06, z=1866.50], EntityMinecartChest['Minecart with Chest'/305666, l='MpServer', x=5326.50, y=17.06, z=1825.50], EntityMooshroom['Mooshroom'/305667, l='MpServer', x=5298.47, y=63.00, z=1847.85], EntityFishCod['Cod'/305676, l='MpServer', x=5291.84, y=56.85, z=1902.62], EntityMooshroom['Mooshroom'/305422, l='MpServer', x=5248.67, y=74.00, z=1884.18], EntityMooshroom['Mooshroom'/305423, l='MpServer', x=5246.96, y=75.00, z=1886.39], EntityMooshroom['Mooshroom'/305672, l='MpServer', x=5330.73, y=63.00, z=1871.82], EntityFishClownfish['Clownfish'/305417, l='MpServer', x=5274.50, y=36.00, z=1946.50], EntityMooshroom['Mooshroom'/305673, l='MpServer', x=5331.71, y=63.00, z=1871.17], EntityFishClownfish['Clownfish'/305418, l='MpServer', x=5271.50, y=36.00, z=1947.50], EntityMooshroom['Mooshroom'/305674, l='MpServer', x=5325.84, y=63.00, z=1882.69], EntityFishClownfish['Clownfish'/305419, l='MpServer', x=5269.61, y=37.20, z=1945.50], EntityFishCod['Cod'/305675, l='MpServer', x=5304.22, y=57.00, z=1900.27], EntityBat['Bat'/305428, l='MpServer', x=5190.57, y=21.03, z=1811.34], EntityFishCod['Cod'/305429, l='MpServer', x=5178.61, y=51.85, z=1813.20], EntityMooshroom['Mooshroom'/305424, l='MpServer', x=5237.53, y=69.00, z=1889.15], EntityMooshroom['Mooshroom'/305425, l='MpServer', x=5245.40, y=74.00, z=1885.80], EntityFishCod['Cod'/305427, l='MpServer', x=5183.52, y=59.73, z=1807.43], EntityFishClownfish['Clownfish'/305436, l='MpServer', x=5185.50, y=51.00, z=1825.50], EntityCreeper['Creeper'/305437, l='MpServer', x=5192.84, y=40.00, z=1847.41], EntitySpider['Spider'/305438, l='MpServer', x=5184.50, y=42.00, z=1848.50], EntitySkeleton['Skeleton'/305439, l='MpServer', x=5196.50, y=40.00, z=1844.50], EntityMooshroom['Mooshroom'/305688, l='MpServer', x=5329.32, y=63.00, z=1886.17], EntityCreeper['Creeper'/305432, l='MpServer', x=5174.50, y=22.00, z=1946.50], EntityFishClownfish['Clownfish'/305434, l='MpServer', x=5199.50, y=54.00, z=1813.50], EntitySkeleton['Skeleton'/305444, l='MpServer', x=5216.50, y=29.00, z=1856.29], EntitySkeleton['Skeleton'/305446, l='MpServer', x=5207.50, y=29.00, z=1851.60], EntitySkeleton['Skeleton'/305440, l='MpServer', x=5190.50, y=41.00, z=1846.50], EntitySquid['Squid'/305442, l='MpServer', x=5199.71, y=51.80, z=1884.44], EntityMooshroom['Mooshroom'/305456, l='MpServer', x=5301.87, y=68.00, z=1832.25], EntityFishCod['Cod'/305492, l='MpServer', x=5202.59, y=46.19, z=1951.25], EntitySkeleton['Skeleton'/305495, l='MpServer', x=5218.23, y=22.00, z=1953.50], EntityCreeper['Creeper'/305490, l='MpServer', x=5213.51, y=17.00, z=1945.82], EntitySpider['Spider'/305491, l='MpServer', x=5212.85, y=16.00, z=1950.67], EntityBat['Bat'/305753, l='MpServer', x=5288.48, y=25.06, z=1911.94], EntityFishCod['Cod'/305498, l='MpServer', x=5200.73, y=48.20, z=1955.33], EntityCreeper['Creeper'/305508, l='MpServer', x=5204.50, y=23.00, z=1904.50], EntityAshen['Ashen'/305509, l='MpServer', x=5203.46, y=16.00, z=1918.24], EntitySkeleton['Skeleton'/305510, l='MpServer', x=5193.51, y=15.00, z=1924.29], EntitySkeleton['Skeleton'/305511, l='MpServer', x=5198.50, y=12.00, z=1924.50], EntityMooshroom['Mooshroom'/305505, l='MpServer', x=5214.40, y=63.00, z=1889.79], EntityMooshroom['Mooshroom'/305506, l='MpServer', x=5219.22, y=64.00, z=1886.83], EntityMooshroom['Mooshroom'/305507, l='MpServer', x=5212.46, y=63.00, z=1893.77], EntitySkeleton['Skeleton'/305517, l='MpServer', x=5200.50, y=12.00, z=1923.67], EntityFishPufferfish['Pufferfish'/305518, l='MpServer', x=5211.69, y=52.20, z=1927.40], EntityFishCod['Cod'/305519, l='MpServer', x=5194.80, y=36.87, z=1941.64], EntityBat['Bat'/305514, l='MpServer', x=5196.67, y=20.10, z=1921.78], EntityFishCod['Cod'/305515, l='MpServer', x=5198.50, y=38.00, z=1930.50], EntityMooshroom['Mooshroom'/305524, l='MpServer', x=5251.14, y=63.00, z=1854.70], EntityMinecartChest['Minecart with Chest'/305520, l='MpServer', x=5207.50, y=13.06, z=1859.50], EntityMinecartChest['Minecart with Chest'/305521, l='MpServer', x=5202.50, y=13.06, z=1859.50], EntityCreeper['Creeper'/305522, l='MpServer', x=5207.48, y=29.00, z=1855.77], EntitySkeleton['Skeleton'/305523, l='MpServer', x=5232.30, y=18.00, z=1859.70], EntityFishCod['Cod'/305532, l='MpServer', x=5271.61, y=40.80, z=1926.80], EntitySquid['Squid'/305530, l='MpServer', x=5277.76, y=49.08, z=1919.01], EntityFishCod['Cod'/305531, l='MpServer', x=5272.36, y=41.18, z=1923.77], EntityMooshroom['Mooshroom'/305536, l='MpServer', x=5253.23, y=65.00, z=1865.33], EntityMooshroom['Mooshroom'/305537, l='MpServer', x=5254.79, y=65.00, z=1864.42], EntityMooshroom['Mooshroom'/305538, l='MpServer', x=5251.77, y=66.00, z=1867.47], EntityMooshroom['Mooshroom'/305539, l='MpServer', x=5246.48, y=70.00, z=1878.23], EntityFishCod['Cod'/305805, l='MpServer', x=5216.19, y=55.85, z=1923.39], EntityFishCod['Cod'/305806, l='MpServer', x=5211.29, y=53.85, z=1924.80], EntityFishCod['Cod'/305807, l='MpServer', x=5206.65, y=52.83, z=1924.65], EntityFishCod['Cod'/305808, l='MpServer', x=5205.50, y=57.00, z=1924.50], EntityFishClownfish['Clownfish'/305554, l='MpServer', x=5230.39, y=38.09, z=1927.39], EntityFishPufferfish['Pufferfish'/305555, l='MpServer', x=5225.67, y=51.11, z=1931.31], EntityFishCod['Cod'/305565, l='MpServer', x=5261.24, y=54.15, z=1923.39], EntityFishCod['Cod'/305566, l='MpServer', x=5258.50, y=51.00, z=1921.50], EntityZombie['Zombie'/305560, l='MpServer', x=5242.50, y=20.00, z=1926.50], EntityBat['Bat'/305561, l='MpServer', x=5228.75, y=19.00, z=1939.75], EntityFishCod['Cod'/305563, l='MpServer', x=5258.50, y=43.00, z=1933.50], EntityItem['item.item.dyePowder.black'/305572, l='MpServer', x=5248.29, y=40.00, z=1942.65], EntityGuardian['Guardian'/305573, l='MpServer', x=5249.50, y=42.00, z=1947.50], EntityFishCod['Cod'/305568, l='MpServer', x=5233.50, y=58.13, z=1944.81], EntitySkeleton['Skeleton'/305580, l='MpServer', x=5225.84, y=29.00, z=1857.71], EntityFishPufferfish['Pufferfish'/305836, l='MpServer', x=5179.31, y=42.20, z=1936.63], EntityFishPufferfish['Pufferfish'/305837, l='MpServer', x=5182.31, y=42.20, z=1936.63], EntityFishPufferfish['Pufferfish'/305838, l='MpServer', x=5181.36, y=40.00, z=1938.28], EntityMinecartChest['Minecart with Chest'/305583, l='MpServer', x=5222.50, y=15.06, z=1855.96], EntitySkeleton['Skeleton'/305834, l='MpServer', x=5306.50, y=20.00, z=1956.50], EntityFishPufferfish['Pufferfish'/305835, l='MpServer', x=5180.50, y=45.72, z=1935.41], EntityBat['Bat'/305588, l='MpServer', x=5268.69, y=19.10, z=1822.87], EntityMooshroom['Mooshroom'/305589, l='MpServer', x=5218.07, y=64.00, z=1894.25], EntityMooshroom['Mooshroom'/305590, l='MpServer', x=5217.56, y=64.00, z=1891.09], EntityMooshroom['Mooshroom'/305591, l='MpServer', x=5215.83, y=64.00, z=1898.59], EntityBat['Bat'/305584, l='MpServer', x=5222.30, y=31.10, z=1850.41], EntityBat['Bat'/305585, l='MpServer', x=5216.17, y=30.10, z=1854.71], EntityMinecartChest['Minecart with Chest'/305586, l='MpServer', x=5255.50, y=32.06, z=1846.50], EntityCreeper['Creeper'/305842, l='MpServer', x=5193.50, y=23.00, z=1825.50], EntityBat['Bat'/305587, l='MpServer', x=5272.75, y=19.10, z=1820.64], EntityCreeper['Creeper'/305843, l='MpServer', x=5194.50, y=23.00, z=1828.50], EntityMinecartChest['Minecart with Chest'/305596, l='MpServer', x=5277.50, y=27.00, z=1825.50], EntityBat['Bat'/305597, l='MpServer', x=5270.39, y=33.10, z=1835.13], EntityMooshroom['Mooshroom'/305599, l='MpServer', x=5234.61, y=69.00, z=1892.89], EntityMooshroom['Mooshroom'/305592, l='MpServer', x=5216.77, y=64.00, z=1898.18], EntityMooshroom['Mooshroom'/305593, l='MpServer', x=5226.22, y=64.00, z=1900.41], EntityMooshroom['Mooshroom'/305594, l='MpServer', x=5221.67, y=64.00, z=1896.15], EntityMooshroom['Mooshroom'/305595, l='MpServer', x=5218.79, y=64.00, z=1892.61], EntityFishCod['Cod'/305609, l='MpServer', x=5200.60, y=56.00, z=1868.79], EntityItem['item.tile.stone.stone'/305365, l='MpServer', x=5251.23, y=51.00, z=1878.44], EntityMooshroom['Mooshroom'/305366, l='MpServer', x=5243.83, y=71.00, z=1893.53], EntityMooshroom['Mooshroom'/305367, l='MpServer', x=5258.16, y=65.00, z=1864.38], EntityFishCod['Cod'/305617, l='MpServer', x=5174.22, y=61.14, z=1892.37], EntityEnderman['Enderman'/305629, l='MpServer', x=5287.50, y=35.00, z=1934.50], EntityFishCod['Cod'/305630, l='MpServer', x=5280.51, y=53.67, z=1932.44], EntityMooshroom['Mooshroom'/305368, l='MpServer', x=5248.77, y=75.00, z=1885.48], EntityBat['Bat'/305636, l='MpServer', x=5266.25, y=27.10, z=1880.45], EntityMinecartChest['Minecart with Chest'/305637, l='MpServer', x=5289.50, y=32.06, z=1823.50], EntityMinecartChest['Minecart with Chest'/305638, l='MpServer', x=5301.50, y=22.06, z=1823.50], EntityMooshroom['Mooshroom'/305639, l='MpServer', x=5292.80, y=68.00, z=1825.44], EntityBat['Bat'/305895, l='MpServer', x=5274.33, y=18.04, z=1803.93], EntityCreeper['Creeper'/305644, l='MpServer', x=5201.50, y=34.00, z=1846.50], EntityMooshroom['Mooshroom'/305640, l='MpServer', x=5289.35, y=69.00, z=1835.84], EntityBat['Bat'/305897, l='MpServer', x=5270.51, y=26.03, z=1855.25], EntityBat['Bat'/305898, l='MpServer', x=5269.40, y=24.34, z=1855.54], EntityZombie['Zombie'/305397, l='MpServer', x=5175.30, y=28.00, z=1842.69], EntityCreeper['Creeper'/305910, l='MpServer', x=5322.50, y=20.00, z=1861.50], EntityFishClownfish['Clownfish'/305399, l='MpServer', x=5182.50, y=51.00, z=1825.50], EntityCreeper['Creeper'/305911, l='MpServer', x=5321.50, y=20.00, z=1860.50], EntityFishCod['Cod'/305650, l='MpServer', x=5329.30, y=55.00, z=1958.77], EntityFishSalmon['Salmon'/305918, l='MpServer', x=5197.26, y=36.96, z=1933.74], EntitySkeleton['Skeleton'/305407, l='MpServer', x=5182.50, y=41.00, z=1846.50], EntityFishSalmon['Salmon'/305919, l='MpServer', x=5194.91, y=35.13, z=1939.28], EntityCreeper['Creeper'/305913, l='MpServer', x=5232.50, y=24.00, z=1855.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1018230272 bytes (971 MB) / 3199205376 bytes (3051 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2707 92 mods loaded, 92 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                             | Version                  | Source                                          | Signature                                |
	|:------ |:------------------------------ |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft                      | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJA | mcp                            | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJA | FML                            | 8.0.99.99                | forge-1.12.2-14.23.4.2707.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                          | 14.23.4.2707             | forge-1.12.2-14.23.4.2707.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | gottagofast                    | 1.1                      | gottagofast-1.1.jar                             | None                                     |
	| UCHIJA | adminshop                      | 1.0                      | adminshop-1.1.jar                               | None                                     |
	| UCHIJA | advancedmortars                | 1.12.2-1.6.20            | advancedmortars-1.12.2-1.6.20.jar               | None                                     |
	| UCHIJA | jei                            | 4.9.2.196                | jei_1.12.2-4.9.2.196.jar                        | None                                     |
	| UCHIJA | appleskin                      | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCHIJA | quark                          | r1.4-123                 | Quark-r1.4-123.jar                              | None                                     |
	| UCHIJA | autoreglib                     | 1.3-17                   | AutoRegLib-1.3-17.jar                           | None                                     |
	| UCHIJA | ichunutil                      | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCHIJA | backtools                      | 7.0.0                    | BackTools-1.12.2-7.0.0.jar                      | None                                     |
	| UCHIJA | baublelicious                  | 1.4.0-4                  | Baublelicious-1.4.0-4.jar                       | None                                     |
	| UCHIJA | baubles                        | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJA | bibliocraft                    | 2.4.4                    | BiblioCraft[v2.4.4][MC1.12.2].jar               | None                                     |
	| UCHIJA | bibliotheca                    | 1.3.3-1.12.2             | bibliotheca-1.3.3-1.12.2.jar                    | None                                     |
	| UCHIJA | bonsaitrees                    | 1.0.5                    | bonsaitrees-1.0.5-b77.jar                       | None                                     |
	| UCHIJA | bookshelf                      | 2.3.544                  | Bookshelf-1.12.2-2.3.544.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | chameleon                      | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJA | ctm                            | MC1.12-0.3.0.15          | CTM-MC1.12-0.3.0.15.jar                         | None                                     |
	| UCHIJA | chisel                         | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCHIJA | chococraft                     | 0.9.1.52                 | chococraft_1.12.1-0.9.1.52.jar                  | None                                     |
	| UCHIJA | codechickenlib                 | 3.1.8.341                | CodeChickenLib-1.12.2-3.1.8.341-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | redstoneflux                   | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | cofhcore                       | 4.5.2                    | CoFHCore-1.12.2-4.5.2.19-universal.jar          | None                                     |
	| UCHIJA | cofhworld                      | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | mantle                         | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCHIJA | tconstruct                     | 1.12.2-2.10.1.84         | TConstruct-1.12.2-2.10.1.84.jar                 | None                                     |
	| UCHIJA | conarm                         | 0.0.20-b                 | conarm-1.12.2-0.0.20-b.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJA | controlling                    | 3.0.6                    | Controlling-3.0.6.jar                           | None                                     |
	| UCHIJA | craftstudioapi                 | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| UCHIJA | crafttweaker                   | 4.1.8                    | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UCHIJA | ctgui                          | 1.0.0                    | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UCHIJA | crafttweakerjei                | 2.0.2                    | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UCHIJA | creeperconfetti                | 1.4.2                    | creeperconfetti-1.4.2.jar                       | None                                     |
	| UCHIJA | ctwatercan                     | 1.12.2-0.4.5             | ctwatercan-1.12.2-0.4.5.jar                     | None                                     |
	| UCHIJA | ding                           | 1.0.1                    | Ding-1.12.1-1.0.1.jar                           | None                                     |
	| UCHIJA | dirt2path                      | 1.7.1                    | dirt2path-1.7.1.jar                             | None                                     |
	| UCHIJA | mcjtylib_ng                    | 3.0.0                    | mcjtylib-1.12-3.0.0.jar                         | None                                     |
	| UCHIJA | efab                           | 0.0.37                   | efab-0.0.37.jar                                 | None                                     |
	| UCHIJA | ebwizardry                     | 4.1.2                    | Electroblob's Wizardry - 4.1.2 - MC 1.12.2.jar  | None                                     |
	| UCHIJA | enderstorage                   | 2.4.3.130                | EnderStorage-1.12.2-2.4.3.130-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | equaldragons                   | 1.1                      | EqualDragons-1.1.jar                            | None                                     |
	| UCHIJA | erebus                         | 1.0.22                   | Erebus-1.0.22.jar                               | None                                     |
	| UCHIJA | fluidfunnel                    | 1.3.0                    | FluidFunnel-1.12.2-1.3.0.jar                    | None                                     |
	| UCHIJA | ftblib                         | 5.1.0.21                 | FTBLib-5.1.0.21.jar                             | None                                     |
	| UCHIJA | ftbutilities                   | 5.1.0.26                 | FTBUtilities-5.1.0.26.jar                       | None                                     |
	| UCHIJA | huntingdim                     | 1.0.24                   | HuntingDimension-1.12.2-1.0.24.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | inspirations                   | 1.12.2-0.1.4             | Inspirations-1.12.2-0.1.4.jar                   | None                                     |
	| UCHIJA | inventorytweaks                | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | ironchest                      | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| UCHIJA | itemscroller                   | 0.11.0                   | itemscroller-1.12.0-0.11.0.jar                  | None                                     |
	| UCHIJA | journeymap                     | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJA | jarm                           | 1.1.1                    | Just+A+Raft+Mod-1.1.1.jar                       | None                                     |
	| UCHIJA | jaff                           | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                   | None                                     |
	| UCHIJA | limelib                        | 1.7.12                   | limelib-1.12.2-1.7.12.jar                       | None                                     |
	| UCHIJA | millenaire                     | Millénaire 6.2.4         | millenaire-6.2.4.jar                            | None                                     |
	| UCHIJA | minicoal                       | 1.0                      | minicoal-1.12.2-1.0.jar                         | None                                     |
	| UCHIJA | testdummy                      | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                      | None                                     |
	| UCHIJA | morpheus                       | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                         | None                                     |
	| UCHIJA | naturescompass                 | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
	| UCHIJA | neat                           | 1.4-15                   | Neat+1.4-15.jar                                 | None                                     |
	| UCHIJA | notenoughwands                 | 1.7.0                    | notenoughwands-1.12-1.7.0.jar                   | None                                     |
	| UCHIJA | openglider                     | @VERSION@                | OpenGlider-1.12.1-1.1.0.jar                     | None                                     |
	| UCHIJA | oreexcavation                  | 1.4.118                  | OreExcavation-1.4.118.jar                       | None                                     |
	| UCHIJA | placebo                        | 1.3.4                    | Placebo-1.12.2-1.3.4.jar                        | None                                     |
	| UCHIJA | thaumcraft                     | 6.1.BETA16               | Thaumcraft-1.12.2-6.1.BETA16.jar                | None                                     |
	| UCHIJA | thermalfoundation              | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | twilightforest                 | 3.7.424                  | twilightforest-1.12.2-3.7.424-universal.jar     | None                                     |
	| UCHIJA | plustic                        | 6.5.2.0                  | plustic-6.5.2.0.jar                             | None                                     |
	| UCHIJA | quickleafdecay                 | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar               | None                                     |
	| UCHIJA | roguelike                      | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
	| UCHIJA | simplecorn                     | 2.4.1                    | SimpleCorn1.12-1.12-2.4.1.jar                   | None                                     |
	| UCHIJA | snad                           | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                      | None                                     |
	| UCHIJA | s                              | 1.0                      | spikey-1.0.0.jar                                | None                                     |
	| UCHIJA | storagedrawers                 | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
	| UCHIJA | tcinventoryscan                | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar      | None                                     |
	| UCHIJA | thaumicjei                     | 1.2.1                    | ThaumicJEI-1.12.2-1.3.1-12.jar                  | None                                     |
	| UCHIJA | thebetweenlands                | 3.3.8                    | TheBetweenlands-3.3.8-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJA | theoneprobe                    | 1.4.23                   | theoneprobe-1.12-1.4.23.jar                     | None                                     |
	| UCHIJA | tinkertoolleveling             | 1.12-1.0.4.DEV.5d716b9   | TinkerToolLeveling-1.12-1.0.4.jar               | None                                     |
	| UCHIJA | toastcontrol                   | 1.6.0                    | Toast Control-1.12.2-1.6.0.jar                  | None                                     |
	| UCHIJA | tombmanygraves2api             | 1.12.2-1.0.0             | tombmanygraves2api-1.12.2-1.0.0.jar             | None                                     |
	| UCHIJA | tombmanygraves                 | 1.12-4.1.0               | TombManyGraves-1.12-4.1.0.jar                   | None                                     |
	| UCHIJA | tombmanypluginsthebetweenlands | 1.0.0                    | tombmanypluginsthebetweenlands-1.0.0.jar        | None                                     |
	| UCHIJA | traverse                       | 1.5.3                    | Traverse-1.12.2-1.5.3-58.jar                    | None                                     |
	| UCHIJA | usefulnullifiers               | 1.4.1                    | usefulnullifiers-1.4.1.jar                      | None                                     |
	| UCHIJA | vanillasatchels                | 1.0.0                    | VanillaSatchels-1.12.2-1.0.0.1-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | venomousfangs                  | 1.1                      | VenomousFangs1.12-1.1.jar                       | None                                     |
	| UCHIJA | waystones                      | 4.0.43                   | Waystones_1.12.2-4.0.43.jar                     | None                                     |
	| UCHIJA | reauth                         | 3.6.0                    | reauth-3.6.0.jar                                | daba0ec4df71b6da841768c49fb873def208a1e3 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
GottaGoFastLoader (gottagofast-1.1.jar)
  com.thiakil.gottagofast.coremod.GottaGoFastASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.11' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)

	Launched Version: forge-14.23.4.2707
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.11, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz`

**Comment by KittenKoder** [comment]
Confirmed, this crash is occurring for one of my server's test players as well.

**Comment by hamza62240** [comment]
Can confirm also.
When I open the Framed Fancy Sign, there is no cursor. Nothing I do brings one up. When I try to exit out of the sign, it just crashes.

It works if the Framed Fancy Sign does not have a block attached.

&nbsp;

One more thing I've noted: **If I do a Ctrl+Middle Click in Creative Mode on a Framed Fancy Sign with text already in it...** It does say +NBT but the text is not saved when I place it. And even if I **don't** apply any texture to it, opening the Fancy Sign GUI will crash it anyway, as long as it was the Ctrl+Middle Clicked Fancy Sign.

This leads me to believe that this is an NBT issue. Please fix it, would be greatly appreciated, as I do use a wood theme from Binnie's Mods for my house.

**Comment by Nuchaz** [comment]
I was able to reproduce this and I am working on a fix. I think I overlooked the framed signs in the last update when I made signs retain their NBT data.

**Comment by Nuchaz** [comment]
I got a fix in place, expect it to be in the next release. I am planning to try and have a bugfix release done within the next few days depending on how it goes.

**Comment by Nuchaz** [comment]
I just released v2.4.5 of BiblioCraft which has fixed this issue.

**Comment by rootli** [comment]
Thanks for looking into it Nuchaz! I use 2.4.5 and I still get the Framed Fancy Sign crash (ArrayIndexOutOfBoundsException). ;-( I attached two crash logs, before and after I installed the latest update. 
The sign is framed by a TechReborn Ruby block.

[crash-2018-06-30_10.49.10-client.txt](https://github.com/Nuchaz/BiblioCraft/files/2151571/crash-2018-06-30_10.49.10-client.txt)
[crash-2018-06-30_10.40.24-client.txt](https://github.com/Nuchaz/BiblioCraft/files/2151572/crash-2018-06-30_10.40.24-client.txt)

[screenshot](https://user-images.githubusercontent.com/7037957/42123631-9e2c8f44-7c55-11e8-8e51-d2c929b522da.png)
I don't know what the GUI usually looks like. In my GUI, I could put items in the two bigger empty slots and they were displayed in the large area (one centred and one to the side). When I click the three tiny empty buttons, it plays a "clack!" audio, but no visual change, and the second or third click crashes. When I press tab, nothing happens, no visual changes, and after the third (?) tab, it crashes.

**Comment by Nuchaz** [comment]
@rootli Is the crash occurring with the same sign as before the update? If so, you may need to destroy that sign and get a new one. The nbt data wasn't been correctly added to the sign on placement, so any signs with that problem that were placed before the update, are still probably gonna be broken.
